name: Devnet Tests

on:
  push:
    branches:
      - next
      - dev
  pull_request:
    branches:
      - next
      - dev
  workflow_dispatch:

concurrency:
  group: devnet-${{ github.ref }}
  cancel-in-progress: true

jobs:
  devnet-deploy-account:
    name: Deploy Account to Devnet
    runs-on: ubuntu-latest
    env:
      AZTEC_ENV: devnet
      AZTEC_VERSION: 4.0.0-devnet.2-patch.1

    steps:
      - name: Checkout repository
        uses: actions/checkout@v5

      - name: Set up Node.js
        uses: actions/setup-node@v4
        with:
          node-version: "22"
          cache: "yarn"

      - name: Install project dependencies
        run: yarn

      - name: Deploy account to devnet
        run: yarn deploy-account::devnet
